name = "bullmer"
compatibility_date = "2024-09-01"
main = "worker.js"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bullmer"
database_id = "985b05ab-3349-4c96-a6d0-11ab7e04abac"
